# Generated by Django 5.1.6 on 2025-02-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_feedetail_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feestructure',
            old_name='amount',
            new_name='yearly_amount',
        ),
        migrations.AddField(
            model_name='feestructure',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
